
CREATE TABLE CERT
(
	NO                   CHAR(18) NOT NULL ,
	NAME                 CHAR(18) NULL ,
	BUILD                CHAR(18) NULL 
);



CREATE UNIQUE INDEX XPK자격증 ON CERT
(NO   ASC);



ALTER TABLE CERT
	ADD CONSTRAINT  XPK자격증 PRIMARY KEY (NO);



CREATE TABLE MEMBER
(
	NO                   CHAR(18) NOT NULL ,
	NAME                 CHAR(18) NULL ,
	ADDRESS              CHAR(18) NULL ,
	TELNO                CHAR(18) NULL ,
	SSN                  CHAR(18) NULL ,
	CERTNO               CHAR(18) NOT NULL 
);



CREATE UNIQUE INDEX XPK회원 ON MEMBER
(NO   ASC);



ALTER TABLE MEMBER
	ADD CONSTRAINT  XPK회원 PRIMARY KEY (NO);



ALTER TABLE MEMBER
	ADD (CONSTRAINT R_2 FOREIGN KEY (CERTNO) REFERENCES CERT (NO));