
CREATE TABLE DEPT4
(
	DEPT_ID              CHAR(18) NOT NULL ,
	DEPT_NAME            CHAR(18) NULL ,
	LOC_ID               CHAR(18) NULL 
);



CREATE UNIQUE INDEX XPK부서 ON DEPT4
(DEPT_ID   ASC);



ALTER TABLE DEPT4
	ADD CONSTRAINT  XPK부서 PRIMARY KEY (DEPT_ID);



CREATE TABLE EMP4
(
	EMP_NO               CHAR(18) NOT NULL ,
	NAME                 CHAR(18) NULL ,
	HIRE                 CHAR(18) NULL ,
	JIKWI                CHAR(18) NULL ,
	SAL                  CHAR(18) NULL ,
	BONUS                CHAR(18) NULL ,
	MGR                  CHAR(18) NULL ,
	DEPT_ID              CHAR(18) NOT NULL 
);



CREATE UNIQUE INDEX XPK사원 ON EMP4
(EMP_NO   ASC);



ALTER TABLE EMP4
	ADD CONSTRAINT  XPK사원 PRIMARY KEY (EMP_NO);



ALTER TABLE EMP4
	ADD (CONSTRAINT R_1 FOREIGN KEY (DEPT_ID) REFERENCES DEPT4 (DEPT_ID));